#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -b &
pgrep -x feh > /dev/null || feh --bg-fill /home/mirai/wallpaper_feh.png &
pgrep -x glava > /dev/null || glava -d &
setxkbmap br abnt2 &
/home/mirai/.config/eww/run.sh &
#/home/mirai/.config/eww/update_spotify_image.sh &
conky --config /home/mirai/.config/conky/config &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width        2
bspc config window_gap          2
bspc config border_radius       10


bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
