local M = {
    ensure_installed = {
        "c",
        "bash",
        "cpp",
        "css",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "html",
        "java",
        "javascript",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "prisma",
        "python",
        "regex",
        "rst",
        "rust",
        "scss",
        "sql",
        "tsx",
        "typescript",
        "v",
        "vim",
        "yuck",
        "zig",
        "markdown",
        "markdown_inline",
    },
    sync_install = false,
    highlight = { enable = true },
    indent = { enable = true },
    autotag = {
        enable = true,
    },
    tree_docs = { enable = true },
}

return M
